### ISSUE TITLE
[BUG] Twitter Download Invalid JSON primitive

### ISSUE THREAD

**Issue by Rootkit-** [AAndyProgram/SCrawler#166]
**Describe the bug**
Doesn't download.

**To Reproduce**
All twitter sites.

<details>
<summary>Log data</summary>
<pre>
2023-09-11 10:26:31: [Twitter] - KoreanMommyDva: data downloading error []
	Invalid JSON primitive: Rate.
2023-09-11 10:26:31: Message: Invalid JSON primitive: Rate.
	HelpLink:
	StackTrace:    at PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage Message, Object OptionalValueReturn)
	at PersonalUtilities.Tools.Web.Documents.JSON.JsonDocument.JParse(String Text, String RootNodeName, WebDocumentEventArgs Args, ErrorsDescriber e)
	at PersonalUtilities.Tools.Web.Documents.JSON.JsonDocument.Parse(String Text)
	at SCrawler.API.Twitter.UserData.DownloadData_Timeline(CancellationToken Token)
</pre>
</details>

**Comment by Rootkit-** [comment]
Must be bug with my install fresh worked

**Comment by AAndyProgram** [comment]
Not confirmed. Can't reproduce.
