### ISSUE TITLE
Incompatible version of Net.Framework  and Twitter data not downloading

### ISSUE THREAD

**Issue by ogfrank33** [AAndyProgram/SCrawler#24]
LOG
```
2022-04-01 01:26:20: [PluginHost.New]
	Could not load file or assembly 'SCrawler.Plugin.LPSG, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
2022-04-01 01:26:20: Message: Could not load file or assembly 'SCrawler.Plugin.LPSG, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
	HelpLink: 
	StackTrace:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
	   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
	   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
	   at SCrawler.Plugin.Hosts.PluginHost..ctor(SFile AssemblyFile, XmlFile& _XML, SFile GlobalPath, XMLValue`1& _Temp, XMLValue`1& _Imgs, XMLValue`1& _Vids)
	-----InnerException 1-----
	
	-----InnerException 2-----
	Message: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
	HelpLink: 
	StackTrace: 
2022-04-01 01:26:20: [PluginHost.New]
	Could not load file or assembly 'SCrawler.Plugin.XVIDEOS, Version=1.0.0.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
2022-04-01 01:26:20: Message: Could not load file or assembly 'SCrawler.Plugin.XVIDEOS, Version=1.0.0.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
	HelpLink: 
	StackTrace:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
	   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
	   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
	   at SCrawler.Plugin.Hosts.PluginHost..ctor(SFile AssemblyFile, XmlFile& _XML, SFile GlobalPath, XMLValue`1& _Temp, XMLValue`1& _Imgs, XMLValue`1& _Vids)
	-----InnerException 1-----
	
	-----InnerException 2-----
	Message: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
	HelpLink: 
	StackTrace: 
2022-04-01 01:32:18: AConvert: Converting Error [19.03.2022 20:27:37] - [String] --> [DateTime]
	[AConvertPartial] Error converting from [String] to [DateTime]
2022-04-01 01:32:18: Message: [AConvertPartial] Error converting from [String] to [DateTime]
	HelpLink: AConvertPartial
	StackTrace:    at PersonalUtilities.Functions.ArgConverter.AConvertPartial(Object Value, Type DestinationType, IFormatProvider Provider)
	   at PersonalUtilities.Functions.ArgConverter.AConvert(Object Value, AModes AMode, Type DestinationType, Boolean IsChecking, Boolean ReturnNullArg, Object NullArg, IFormatProvider Provider, ErrorsDescriber e)
	-----InnerException 1-----
	
	-----InnerException 2-----
	Message: Format Provider [ANumbers] does not supported
	HelpLink: 0
	StackTrace:    at PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage _Message, Object OptionalValueReturn)
	   at PersonalUtilities.Functions.ArgConverter.ADateTime.Parse(String Value, Type DestinationType, String Pattern, IFormatProvider Provider, Nullable`1 Style, TimeModes TimeMode, Object NothingArg, ErrorsDescriber e)
	   at PersonalUtilities.Functions.ArgConverter.AConvertPartial(Object Value, Type DestinationType, IFormatProvider Provider)
2022-04-01 01:35:32: AConvert: Converting Error [19.03.2022 20:27:37] - [String] --> [DateTime]
	[AConvertPartial] Error converting from [String] to [DateTime]
2022-04-01 01:35:32: Message: [AConvertPartial] Error converting from [String] to [DateTime]
	HelpLink: AConvertPartial
	StackTrace:    at PersonalUtilities.Functions.ArgConverter.AConvertPartial(Object Value, Type DestinationType, IFormatProvider Provider)
	   at PersonalUtilities.Functions.ArgConverter.AConvert(Object Value, AModes AMode, Type DestinationType, Boolean IsChecking, Boolean ReturnNullArg, Object NullArg, IFormatProvider Provider, ErrorsDescriber e)
	-----InnerException 1-----
	
	-----InnerException 2-----
	Message: Format Provider [ANumbers] does not supported
	HelpLink: 0
	StackTrace:    at PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage _Message, Object OptionalValueReturn)
	   at PersonalUtilities.Functions.ArgConverter.ADateTime.Parse(String Value, Type DestinationType, String Pattern, IFormatProvider Provider, Nullable`1 Style, TimeModes TimeMode, Object NothingArg, ErrorsDescriber e)
	   at PersonalUtilities.Functions.ArgConverter.AConvertPartial(Object Value, Type DestinationType, IFormatProvider Provider)
```

**Comment by AAndyProgram** [comment]
Not enough information!
Write what you are using: OS, architecture (x64 or x86), NET.Framework version, path to SCrawler, steps to reproduce the error.

**Comment by ogfrank33** [comment]
https://www.dropbox.com/s/1b07tmceadzz6qy/screen-capture%20%281%29.mp4?dl=0

**Comment by AAndyProgram** [comment]
I saw your video.
1. After adding a user, you need to click the ```Download button``` or how does the download of this user begin?!
2. As I can see, you have NET.Framework 4.8 downloaded. SCrawler requires version **[4.6.1](https://github.com/AAndyProgram/SCrawler#requirements)** or higher. This means that 4.6.1 must be installed in any case. I will update the requirements chapter later.

[Download NET.Framework 4.6.1](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net461)

**Comment by ogfrank33** [comment]
When I download NET Framework 4.6.1 it says since the latest version is downloaded that 4.6.1 is already installed. Yes, I didn't click download all. I just now did it and it worked. Problem solved.

**Comment by ogfrank33** [comment]
https://www.dropbox.com/s/3vi00eci31ebzj5/screen-capture%202.mp4?dl=0

**Comment by AAndyProgram** [comment]
Okay
