### ISSUE TITLE
ArchiveSCrawlerUsersDataFiles.bat help needed

### ISSUE THREAD

**Issue by tayser1** [AAndyProgram/SCrawler#27]
I used version 2.0.0.4 now I downloaded and started version 3.0.0.6 and nothing works.
How to fix that. I read that I have to archive the user.xml, but the bat file isn't working.

Do I have to delete all data and start from the beginning?

**Comment by tayser1** [comment]
2022-04-04 18:45:23: AConvert: Converting Error [Reddit] - [String] --> [Int32]
	[AConvertPartial] Error converting from [String] to [Int32]
2022-04-04 18:45:23: Message: [AConvertPartial] Error converting from [String] to [Int32]
	HelpLink: AConvertPartial
	StackTrace:    at PersonalUtilities.Functions.ArgConverter.AConvertPartial(Object Value, Type DestinationType, IFormatProvider Provider)
	   at PersonalUtilities.Functions.ArgConverter.AConvert(Object Value, AModes AMode, Type DestinationType, Boolean IsChecking, Boolean ReturnNullArg, Object NullArg, IFormatProvider Provider, ErrorsDescriber e)
	-----InnerException 1-----
	
	-----InnerException 2-----
	Message: Conversion Value [Reddit] to type [Int32] if failed
	HelpLink: 
	StackTrace:    at PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage _Message, Object OptionalValueReturn)
	   at PersonalUtilities.Functions.ArgConverter.ANumbers.Parse(String Value, Type DestinationType, IFormatProvider Provider, NumberStyles Style, Object NothingArg, ErrorsDescriber e)
	   at PersonalUtilities.Functions.ArgConverter.AConvertPartial(Object Value, Type DestinationType, IFormatProvider Provider)

**Comment by AAndyProgram** [comment]
OMB, obviously you need to have a basic knowledge of BAT to use this tool! This is an example. This is just for help. If you can't use it, you can archive your data with whatever tool you're comfortable with.
Besides, it's not necessary.

Why do you need to delete all data? Just update the program to the latest version and continue using it. But yes, you can delete all data and start from the beginning, if you want to.

BTW, the log looks incomplete.

**Comment by AAndyProgram** [comment]
Since I didn't receive your reply, I consider this issue resolved.
