### ISSUE TITLE
Twitter always fails with 400 (Bad Request)

### ISSUE THREAD

**Issue by DimoNline** [AAndyProgram/SCrawler#3]
Here's logs

```
	-----InnerException 1-----
	
	-----InnerException 2-----
	Message: The remote server returned an error: (400) Bad Request.
	HelpLink: 
	StackTrace:    at System.Net.HttpWebRequest.GetResponse()
	   at PersonalUtilities.Tools.WEB.Response.GetResponse(String URL, String PayLoad, ErrorsDescriber e)
2021-12-22 15:37:06: Twitter - *: data downloading error [https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=*&count=200&exclude_replies=false&include_rts=1&tweet_mode=extended]
	[Response.GetResponse]:
	400 (BadRequest)
	URL: [https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=*&count=200&exclude_replies=false&include_rts=1&tweet_mode=extended]
	The remote server returned an error: (400) Bad Request.
2021-12-22 15:37:06: Message: [Response.GetResponse]:
	400 (BadRequest)
	URL: [https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=*&count=200&exclude_replies=false&include_rts=1&tweet_mode=extended]
	The remote server returned an error: (400) Bad Request.
	HelpLink: 
	StackTrace:    at PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage _Message, Object OptionalValueReturn)
	   at PersonalUtilities.Tools.WEB.Response.ReturnError(Exception& ex, ErrorsDescriber e, String URL)
	   at PersonalUtilities.Tools.WEB.Response.GetResponse(String URL, String PayLoad, ErrorsDescriber e)
	   at SCrawler.API.Twitter.UserData.DownloadData(String POST, CancellationToken Token)
	-----InnerException 1-----
	
	-----InnerException 2-----
	Message: The remote server returned an error: (400) Bad Request.
	HelpLink: 
	StackTrace:    at System.Net.HttpWebRequest.GetResponse()
	   at PersonalUtilities.Tools.WEB.Response.GetResponse(String URL, String PayLoad, ErrorsDescriber e)

```

**Comment by AAndyProgram** [comment]
This means that you have set up incorrect Twitter credentials or haven't configured them.
[Twitter settings](https://github.com/AAndyProgram/SCrawler/wiki/Settings#twitter-settings) (all fields are required):
- Cookies
- Token - x-csrf-token
- Authorization - bearer token

**Comment by AAndyProgram** [comment]
I just wrote a guide for finding tokens.
https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-find-tokens
