### ISSUE TITLE
Error opening session cookie in editor

### ISSUE THREAD

**Issue by IQ1998** [AAndyProgram/SCrawler#38]
**Describe the bug**
Instagram credentials keeps expired. When I go back to check the cookies, there is a `rur` cookie that produce error so I think this might be the case

**To Reproduce**
1. Download [SCrawler_3.0.0.9_x86.zip](https://github.com/AAndyProgram/SCrawler/releases/download/3.0.0.9/SCrawler_3.0.0.9_x86.zip)
2. Go to instagram, open the Developer tools and copy all the cookies, my cookies are the following: `rur`, `shbid`, `shbts`, `sessionid`, `csrftoken`, `ig_nrcb`, `ds_user_id`, `ig_did`, `mid`. 
3. I only need to download posts so I don't add `Hash2`, `x-ig-app-id`, `ix-ig-www-claim` and `Saved posts user`. I only reload to get the `Hash`.
4. I add a new User using this url format `https://www.instagram.com/SomeUserName`
5. I click `Download selected` and I see nothing being downloaded. Checking log show me that `Instagram credentials have expired`
6. I go back to Instagram settings to check any issue. When I click on the `rur` cookie (which has the value of `"EAG\0543019457599\0541683004771:01f7a6bc68dbceae15c578c56a7373aae35b5d8976bc686833b96e4cf94606cdb3647372"`) I see this error:

```
Message: Value of '1/1/0001 12:00:00 AM' is not valid for 'Value'. 'Value' should be between 'MinDate' and 'MaxDate'.
Parameter name: Value
HelpLink: 
StackTrace:    at System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
   at PersonalUtilities.Forms.Controls.TextBoxExtended.set_Value(Object NewValue)
   at PersonalUtilities.Tools.WEB.CookieEditorForm.CookieEditorForm_Load(Object sender, EventArgs e)
```

Checking the log produce this:
```
2022-05-02 12:48:11: AConvert: Converting Error [19.03.2022 20:27:37] - [String] --> [DateTime]
	[AConvertPartial] Error converting from [String] to [DateTime]
2022-05-02 12:48:11: Message: [AConvertPartial] Error converting from [String] to [DateTime]
	HelpLink: AConvertPartial
	StackTrace:    at PersonalUtilities.Functions.ArgConverter.AConvertPartial(Object Value, Type DestinationType, IFormatProvider Provider)
	   at PersonalUtilities.Functions.ArgConverter.AConvert(Object Value, AModes AMode, Type DestinationType, Boolean IsChecking, Boolean ReturnNullArg, Object NullArg, IFormatProvider Provider, ErrorsDescriber e)
	-----InnerException 1-----
	
	-----InnerException 2-----
	Message: Format Provider [ANumbers] does not supported
	HelpLink: 0
	StackTrace:    at PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage _Message, Object OptionalValueReturn)
	   at PersonalUtilities.Functions.ArgConverter.ADateTime.Parse(String Value, Type DestinationType, String Pattern, IFormatProvider Provider, Nullable`1 Style, TimeModes TimeMode, Object NothingArg, ErrorsDescriber e)
	   at PersonalUtilities.Functions.ArgConverter.AConvertPartial(Object Value, Type DestinationType, IFormatProvider Provider)
2022-05-02 12:48:11: Form loading error
	Value of '1/1/0001 12:00:00 AM' is not valid for 'Value'. 'Value' should be between 'MinDate' and 'MaxDate'.
	Parameter name: Value
2022-05-02 12:48:11: Message: Value of '1/1/0001 12:00:00 AM' is not valid for 'Value'. 'Value' should be between 'MinDate' and 'MaxDate'.
	Parameter name: Value
	HelpLink: 
	StackTrace:    at System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
	   at PersonalUtilities.Forms.Controls.TextBoxExtended.set_Value(Object NewValue)
	   at PersonalUtilities.Tools.WEB.CookieEditorForm.CookieEditorForm_Load(Object sender, EventArgs e)
```

**Expected behavior**
Getting cookie to work so I run the download.

**Release information (please complete the following information):**
 - OS Windows 10
 - Architecture x86
 - Version 3.0.0.9
 - NET.Framework version 4.8

If I did anything wrong I apologize for wasting anyone time. I have checked the issue I find nothing. Thank you for any help

**Comment by AAndyProgram** [comment]
Got it. Confirmed. But this is not a bug.
1. Cookies don't need to be updated frequently. It is enough to update cookies **every 3 months**.
2. Don't use the cookie editor. Always use the [default way](https://github.com/AAndyProgram/SCrawler/wiki/Settings#how-to-set-up-cookies) to add cookies.
3. This error may appear when opening a session cookie in the editor. If it's a session cookie, it doesn't have a date. The cookie parser can manage it, but the cookie editor can't.

**Just always use the default way to add cookies.**
