### ISSUE TITLE
"ControlInvokeFast" error in log [BUG]

### ISSUE THREAD

**Issue by TGJ64** [AAndyProgram/SCrawler#82]
In the 2022.10.23.0 version, I seem to get this error in the log sometimes and I'm not sure what it means:

2022-10-29 13:11:29: [ControlInvokeFast]
	Operation is not valid due to the current state of the object.
2022-10-29 13:11:29: [ControlInvokeFast]
	Operation is not valid due to the current state of the object.
2022-10-29 13:11:29: Message: Operation is not valid due to the cu
ent state of the object.
	HelpLink: 
	StackTrace:    at System.Windows.Forms.Layout.TableLayout.SorterObjectArray.SwapIfGreaterWithItems(Int32 a, Int32 b)
	   at System.Windows.Forms.Layout.TableLayout.SorterObjectArray.QuickSort(Int32 left, Int32 right)
	   at System.Windows.Forms.Layout.TableLayout.Sort(Object[] array, IComparer comparer)
	   at System.Windows.Forms.Layout.TableLayout.ContainerInfo.get_FixedChildrenInfo()
	   at System.Windows.Forms.Layout.TableLayout.xAssignRowsAndColumns(ContainerInfo containerInfo, LayoutInfo[] childrenInfo, Int32 maxColumns, Int32 maxRows, TableLayoutPanelGrowStyle growStyle)
	   at System.Windows.Forms.Layout.TableLayout.AssignRowsAndColumns(ContainerInfo containerInfo)
	   at System.Windows.Forms.Layout.TableLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
	   at System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
	   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
	   at System.Windows.Forms.TableLayoutPanel.OnLayout(LayoutEventArgs levent)
	   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
	   at System.Windows.Forms.Control.PerformLayout()
	   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
	   at System.Windows.Forms.Layout.LayoutTransaction.Dispose()
	   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
	   at PersonalUtilities.Functions.UniversalFunctions.ControlInvokeFast(Control Control, Action Method, ErrorsDescriber e)

**Comment by AAndyProgram** [comment]
This is not a bug. I added this on purpose. I can't determine one internal error. This doesn't affect the operation of SCrawler in any way.
